name: tests

on: [push]

jobs:
  test:

    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.6.x', '3.7.x', '3.8.x']
        os: [ubuntu-18.04, ubuntu-16.04, macOS-10.14]

    steps:
    - uses: actions/checkout@master
      with:
        lfs: true
        
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install anchor
      run: pip install -e ".[test]"
      env:
        AIRES_RUN_DIR: ${GITHUB_WORKSPACE}
	
    - name: Running pytest
      run: python -m pytest tests
      env:
        AIRES_RUN_DIR: ${GITHUB_WORKSPACE}